server:
  port: 8190

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.164.164.164:10084
      config:
        server-addr: 10.164.164.164:10084
        import-check:
          enabled: false